### ISSUE TITLE
Include Icon in Executable

### ISSUE THREAD

**Issue by johannesvollmer** [olback/tray-item-rs#5]
Hi!

Is it possible to create the icon from bytes? I'd like to use `include_bytes!` in order to avoid having to create an installer that puts an `.ico` file somewhere.

**Comment by olback** [comment]
It's currently not possible with `include_bytes!`. You can use a Windows resource file (`.rc`) to accomplish this.

Since Rust does not yet natively support `.rc` files, you have to use third-party libraries such as [windres](https://docs.rs/windres/0.2.2/windres/) or [winres](https://docs.rs/winres/0.1.11/winres/).

**Comment by johannesvollmer** [comment]
Okay thanks :)
